In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3,4,5,6])

In [3]:
b=np.array([7,8,9,4,5,6])

slice 

In [13]:
a[::2] # step for index 0 to last but by step 2

array([1, 3, 5])

In [14]:
a[:] # select all element for list

array([1, 2, 3, 4, 5, 6])

In [15]:
a[:3] # select element till index 3

array([1, 2, 3])

In [16]:
a[3:4] 

array([4])

In [19]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x[1:2,:] # select 2nd row

array([[4, 5, 6]])

In [36]:
x[[1,2,0],[1,2,1]] # fanicy indexing 

array([5, 9, 2])

Information

In [37]:
x.shape

(3, 3)

In [38]:
x.ndim

2

In [39]:
x.size

9

In [40]:
x.dtype

dtype('int32')

In [47]:
len(x) # length of array element

3

arithmetic operation

In [48]:
a-b

array([-6, -6, -6,  0,  0,  0])

In [49]:
a+b

array([ 8, 10, 12,  8, 10, 12])

In [50]:
a/b

array([0.14285714, 0.25      , 0.33333333, 1.        , 1.        ,
       1.        ])

In [51]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [52]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [53]:
a.dot(b)

127

comparison

In [54]:
a==b

array([False, False, False,  True,  True,  True])

In [57]:
a<3

array([ True,  True, False, False, False, False])

aggregate 

In [59]:
np.sum(a)

21

In [60]:
a.sum()

21

In [63]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.sum(x,axis=0) # adding columns 

array([12, 15, 18])

In [65]:
np.sum(x[1:2,0:1]) # adding define 

4

In [ ]:
x.max()